/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 134
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_fn = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DASH_GT = 5,
  anon_sym_COLON = 6,
  anon_sym_let = 7,
  anon_sym_EQ = 8,
  anon_sym_type = 9,
  anon_sym_COMMA = 10,
  sym_type_u8 = 11,
  sym_type_u16 = 12,
  sym_type_u32 = 13,
  sym_type_u64 = 14,
  sym_type_i8 = 15,
  sym_type_i16 = 16,
  sym_type_i32 = 17,
  sym_type_i64 = 18,
  sym_type_f32 = 19,
  sym_type_f64 = 20,
  sym_type_bool = 21,
  sym_number = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_token1 = 24,
  anon_sym_DQUOTE_DQUOTE = 25,
  sym_identifier = 26,
  sym_newline = 27,
  sym_indent = 28,
  sym_dedent = 29,
  sym_source_file = 30,
  sym__statement = 31,
  sym_function_definition = 32,
  sym_let_statement = 33,
  sym_type_statement = 34,
  sym_parameters = 35,
  sym_parameter = 36,
  sym_type_annotation = 37,
  sym_expression = 38,
  sym_call_expression = 39,
  sym_arguments = 40,
  sym_string = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_parameters_repeat1 = 43,
  aux_sym_arguments_repeat1 = 44,
  aux_sym_string_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_type] = "type",
  [anon_sym_COMMA] = ",",
  [sym_type_u8] = "type_u8",
  [sym_type_u16] = "type_u16",
  [sym_type_u32] = "type_u32",
  [sym_type_u64] = "type_u64",
  [sym_type_i8] = "type_i8",
  [sym_type_i16] = "type_i16",
  [sym_type_i32] = "type_i32",
  [sym_type_i64] = "type_i64",
  [sym_type_f32] = "type_f32",
  [sym_type_f64] = "type_f64",
  [sym_type_bool] = "type_bool",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE_DQUOTE] = "\"\"",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_function_definition] = "function_definition",
  [sym_let_statement] = "let_statement",
  [sym_type_statement] = "type_statement",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_type_annotation] = "type_annotation",
  [sym_expression] = "expression",
  [sym_call_expression] = "call_expression",
  [sym_arguments] = "arguments",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_type_u8] = sym_type_u8,
  [sym_type_u16] = sym_type_u16,
  [sym_type_u32] = sym_type_u32,
  [sym_type_u64] = sym_type_u64,
  [sym_type_i8] = sym_type_i8,
  [sym_type_i16] = sym_type_i16,
  [sym_type_i32] = sym_type_i32,
  [sym_type_i64] = sym_type_i64,
  [sym_type_f32] = sym_type_f32,
  [sym_type_f64] = sym_type_f64,
  [sym_type_bool] = sym_type_bool,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_function_definition] = sym_function_definition,
  [sym_let_statement] = sym_let_statement,
  [sym_type_statement] = sym_type_statement,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_type_annotation] = sym_type_annotation,
  [sym_expression] = sym_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_arguments] = sym_arguments,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_type_u8] = {
    .visible = true,
    .named = true,
  },
  [sym_type_u16] = {
    .visible = true,
    .named = true,
  },
  [sym_type_u32] = {
    .visible = true,
    .named = true,
  },
  [sym_type_u64] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i8] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i16] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i32] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i64] = {
    .visible = true,
    .named = true,
  },
  [sym_type_f32] = {
    .visible = true,
    .named = true,
  },
  [sym_type_f64] = {
    .visible = true,
    .named = true,
  },
  [sym_type_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_type_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 7,
  [8] = 4,
  [9] = 7,
  [10] = 3,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 11,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 12,
  [22] = 19,
  [23] = 14,
  [24] = 15,
  [25] = 16,
  [26] = 18,
  [27] = 13,
  [28] = 20,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 34,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 39,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 50,
  [51] = 41,
  [52] = 42,
  [53] = 53,
  [54] = 43,
  [55] = 40,
  [56] = 50,
  [57] = 45,
  [58] = 48,
  [59] = 46,
  [60] = 37,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 62,
  [78] = 78,
  [79] = 79,
  [80] = 70,
  [81] = 81,
  [82] = 69,
  [83] = 78,
  [84] = 84,
  [85] = 53,
  [86] = 74,
  [87] = 68,
  [88] = 75,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 90,
  [98] = 98,
  [99] = 92,
  [100] = 93,
  [101] = 101,
  [102] = 76,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 96,
  [109] = 109,
  [110] = 98,
  [111] = 103,
  [112] = 112,
  [113] = 113,
  [114] = 94,
  [115] = 115,
  [116] = 104,
  [117] = 107,
  [118] = 91,
  [119] = 106,
  [120] = 89,
  [121] = 101,
  [122] = 115,
  [123] = 109,
  [124] = 124,
  [125] = 113,
  [126] = 95,
  [127] = 127,
  [128] = 124,
  [129] = 84,
  [130] = 112,
  [131] = 72,
  [132] = 127,
  [133] = 133,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 62,
        '(', 29,
        ')', 30,
        ',', 36,
        '-', 16,
        '/', 4,
        ':', 32,
        '=', 34,
        'b', 21,
        'f', 10,
        'i', 5,
        'l', 17,
        't', 24,
        'u', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '/') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(61);
      if (lookahead == ')') ADVANCE(30);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'b') ADVANCE(80);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'i') ADVANCE(67);
      if (lookahead == 'u') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(8);
      if (lookahead == '6') ADVANCE(12);
      if (lookahead == '8') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '1') ADVANCE(15);
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(13);
      if (lookahead == '8') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(41);
      END_STATE();
    case 10:
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == '4') ADVANCE(51);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(43);
      END_STATE();
    case 14:
      if (lookahead == '6') ADVANCE(47);
      END_STATE();
    case 15:
      if (lookahead == '6') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_type_u8);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_type_u8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_type_u16);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_type_u16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_type_u32);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_type_u32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_type_u64);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_type_u64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_type_i8);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_type_i8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_type_i16);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_type_i16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_type_i32);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_type_i32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_type_i64);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_type_i64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_type_f32);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_type_f32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_type_f64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_type_f64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_type_bool);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_type_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(63);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(76);
      if (lookahead == '3') ADVANCE(70);
      if (lookahead == '6') ADVANCE(74);
      if (lookahead == '8') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(77);
      if (lookahead == '3') ADVANCE(71);
      if (lookahead == '6') ADVANCE(75);
      if (lookahead == '8') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(69);
      if (lookahead == '6') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0, .external_lex_state = 3},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0, .external_lex_state = 3},
  [86] = {.lex_state = 0, .external_lex_state = 3},
  [87] = {.lex_state = 0, .external_lex_state = 3},
  [88] = {.lex_state = 0, .external_lex_state = 3},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0, .external_lex_state = 3},
  [92] = {.lex_state = 0, .external_lex_state = 3},
  [93] = {.lex_state = 0, .external_lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0, .external_lex_state = 4},
  [99] = {.lex_state = 0, .external_lex_state = 3},
  [100] = {.lex_state = 0, .external_lex_state = 3},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 3},
  [103] = {.lex_state = 0, .external_lex_state = 4},
  [104] = {.lex_state = 0, .external_lex_state = 3},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0, .external_lex_state = 3},
  [107] = {.lex_state = 0, .external_lex_state = 3},
  [108] = {.lex_state = 0, .external_lex_state = 3},
  [109] = {.lex_state = 0, .external_lex_state = 4},
  [110] = {.lex_state = 0, .external_lex_state = 4},
  [111] = {.lex_state = 0, .external_lex_state = 4},
  [112] = {.lex_state = 0, .external_lex_state = 4},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0, .external_lex_state = 3},
  [117] = {.lex_state = 0, .external_lex_state = 3},
  [118] = {.lex_state = 0, .external_lex_state = 3},
  [119] = {.lex_state = 0, .external_lex_state = 3},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0, .external_lex_state = 4},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0, .external_lex_state = 4},
  [131] = {.lex_state = 0, .external_lex_state = 3},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_type_u8] = ACTIONS(1),
    [sym_type_u16] = ACTIONS(1),
    [sym_type_u32] = ACTIONS(1),
    [sym_type_u64] = ACTIONS(1),
    [sym_type_i8] = ACTIONS(1),
    [sym_type_i16] = ACTIONS(1),
    [sym_type_i32] = ACTIONS(1),
    [sym_type_i64] = ACTIONS(1),
    [sym_type_f32] = ACTIONS(1),
    [sym_type_f64] = ACTIONS(1),
    [sym_type_bool] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(105),
    [sym__statement] = STATE(29),
    [sym_function_definition] = STATE(29),
    [sym_let_statement] = STATE(29),
    [sym_type_statement] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_type] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(126), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [21] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(113), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [42] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(100), 1,
      sym_type_annotation,
    ACTIONS(17), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [63] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(71), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(95), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(122), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(93), 1,
      sym_type_annotation,
    ACTIONS(17), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [147] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(115), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(125), 1,
      sym_type_annotation,
    ACTIONS(15), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [189] = 6,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(27), 1,
      sym_dedent,
    STATE(27), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [212] = 6,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(34), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(40), 1,
      anon_sym_type,
    STATE(12), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [235] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [258] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(47), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_dedent,
    STATE(15), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [281] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [304] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(51), 1,
      sym_dedent,
    ACTIONS(53), 1,
      sym_comment,
    STATE(18), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [327] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(55), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_dedent,
    STATE(13), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [350] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [373] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(45), 1,
      sym_dedent,
    ACTIONS(59), 1,
      sym_comment,
    STATE(20), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [396] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [419] = 6,
    ACTIONS(29), 1,
      sym_dedent,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_fn,
    ACTIONS(69), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_type,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [442] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_dedent,
    STATE(28), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [465] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_dedent,
    STATE(24), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [488] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [511] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(83), 1,
      sym_dedent,
    ACTIONS(85), 1,
      sym_comment,
    STATE(26), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [534] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(27), 1,
      sym_dedent,
    ACTIONS(43), 1,
      sym_comment,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [557] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [580] = 6,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_dedent,
    STATE(21), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [603] = 6,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      sym_comment,
    STATE(12), 5,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      sym_type_statement,
      aux_sym_source_file_repeat1,
  [626] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(63), 1,
      sym_expression,
    STATE(90), 1,
      sym_arguments,
    STATE(68), 2,
      sym_call_expression,
      sym_string,
  [652] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_expression,
    STATE(97), 1,
      sym_arguments,
    STATE(68), 2,
      sym_call_expression,
      sym_string,
  [678] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(92), 1,
      sym_expression,
    STATE(87), 2,
      sym_call_expression,
      sym_string,
  [698] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(99), 1,
      sym_expression,
    STATE(87), 2,
      sym_call_expression,
      sym_string,
  [718] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(108), 1,
      sym_expression,
    STATE(87), 2,
      sym_call_expression,
      sym_string,
  [738] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(79), 1,
      sym_expression,
    STATE(68), 2,
      sym_call_expression,
      sym_string,
  [758] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(96), 1,
      sym_expression,
    STATE(87), 2,
      sym_call_expression,
      sym_string,
  [778] = 1,
    ACTIONS(109), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [786] = 4,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(115), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [800] = 1,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [808] = 1,
    ACTIONS(120), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [816] = 1,
    ACTIONS(122), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [824] = 1,
    ACTIONS(124), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [832] = 1,
    ACTIONS(126), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [840] = 1,
    ACTIONS(118), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [848] = 1,
    ACTIONS(128), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [856] = 4,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_repeat1,
    ACTIONS(132), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [870] = 1,
    ACTIONS(134), 5,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [878] = 4,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(138), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [892] = 1,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [900] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(61), 1,
      sym_parameter,
    STATE(128), 1,
      sym_parameters,
  [916] = 1,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [924] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 4,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_COMMA,
  [942] = 1,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [950] = 1,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [958] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      sym_parameter,
    STATE(124), 1,
      sym_parameters,
  [974] = 1,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [982] = 4,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(138), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [996] = 4,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_repeat1,
    ACTIONS(152), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [1010] = 1,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_type,
  [1018] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
  [1031] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1042] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_arguments_repeat1,
  [1055] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_parameters_repeat1,
  [1068] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_arguments_repeat1,
  [1081] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_arguments_repeat1,
  [1094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_parameters_repeat1,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1115] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_DASH_GT,
    ACTIONS(182), 1,
      anon_sym_COLON,
  [1125] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COLON,
    ACTIONS(186), 1,
      anon_sym_EQ,
  [1135] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1143] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1183] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_newline,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
  [1193] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_DASH_GT,
    ACTIONS(202), 1,
      anon_sym_COLON,
  [1203] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1211] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COLON,
    ACTIONS(206), 1,
      anon_sym_EQ,
  [1221] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(73), 1,
      sym_parameter,
  [1231] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_DASH_GT,
    ACTIONS(210), 1,
      anon_sym_COLON,
  [1241] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_DASH_GT,
    ACTIONS(214), 1,
      anon_sym_COLON,
  [1251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LPAREN,
  [1258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_newline,
  [1265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_newline,
  [1272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_newline,
  [1279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      sym_newline,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_identifier,
  [1293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
  [1300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      sym_newline,
  [1307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_newline,
  [1314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_newline,
  [1321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_EQ,
  [1328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_COLON,
  [1335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_newline,
  [1342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
  [1349] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_indent,
  [1356] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_newline,
  [1363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_newline,
  [1370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      sym_identifier,
  [1377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_newline,
  [1384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      sym_indent,
  [1391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      sym_newline,
  [1398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
  [1405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_newline,
  [1412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_newline,
  [1419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_newline,
  [1426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_indent,
  [1433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_indent,
  [1440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      sym_indent,
  [1447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_indent,
  [1454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_COLON,
  [1461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_EQ,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_EQ,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_newline,
  [1482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      sym_newline,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_newline,
  [1496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_newline,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
  [1510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_identifier,
  [1517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_EQ,
  [1524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_indent,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_COLON,
  [1545] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_COLON,
  [1552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      sym_identifier,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
  [1566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_LPAREN,
  [1573] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_indent,
  [1580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym_newline,
  [1587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym_identifier,
  [1594] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 147,
  [SMALL_STATE(10)] = 168,
  [SMALL_STATE(11)] = 189,
  [SMALL_STATE(12)] = 212,
  [SMALL_STATE(13)] = 235,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 281,
  [SMALL_STATE(16)] = 304,
  [SMALL_STATE(17)] = 327,
  [SMALL_STATE(18)] = 350,
  [SMALL_STATE(19)] = 373,
  [SMALL_STATE(20)] = 396,
  [SMALL_STATE(21)] = 419,
  [SMALL_STATE(22)] = 442,
  [SMALL_STATE(23)] = 465,
  [SMALL_STATE(24)] = 488,
  [SMALL_STATE(25)] = 511,
  [SMALL_STATE(26)] = 534,
  [SMALL_STATE(27)] = 557,
  [SMALL_STATE(28)] = 580,
  [SMALL_STATE(29)] = 603,
  [SMALL_STATE(30)] = 626,
  [SMALL_STATE(31)] = 652,
  [SMALL_STATE(32)] = 678,
  [SMALL_STATE(33)] = 698,
  [SMALL_STATE(34)] = 718,
  [SMALL_STATE(35)] = 738,
  [SMALL_STATE(36)] = 758,
  [SMALL_STATE(37)] = 778,
  [SMALL_STATE(38)] = 786,
  [SMALL_STATE(39)] = 800,
  [SMALL_STATE(40)] = 808,
  [SMALL_STATE(41)] = 816,
  [SMALL_STATE(42)] = 824,
  [SMALL_STATE(43)] = 832,
  [SMALL_STATE(44)] = 840,
  [SMALL_STATE(45)] = 848,
  [SMALL_STATE(46)] = 856,
  [SMALL_STATE(47)] = 870,
  [SMALL_STATE(48)] = 878,
  [SMALL_STATE(49)] = 892,
  [SMALL_STATE(50)] = 900,
  [SMALL_STATE(51)] = 916,
  [SMALL_STATE(52)] = 924,
  [SMALL_STATE(53)] = 932,
  [SMALL_STATE(54)] = 942,
  [SMALL_STATE(55)] = 950,
  [SMALL_STATE(56)] = 958,
  [SMALL_STATE(57)] = 974,
  [SMALL_STATE(58)] = 982,
  [SMALL_STATE(59)] = 996,
  [SMALL_STATE(60)] = 1010,
  [SMALL_STATE(61)] = 1018,
  [SMALL_STATE(62)] = 1031,
  [SMALL_STATE(63)] = 1042,
  [SMALL_STATE(64)] = 1055,
  [SMALL_STATE(65)] = 1068,
  [SMALL_STATE(66)] = 1081,
  [SMALL_STATE(67)] = 1094,
  [SMALL_STATE(68)] = 1107,
  [SMALL_STATE(69)] = 1115,
  [SMALL_STATE(70)] = 1125,
  [SMALL_STATE(71)] = 1135,
  [SMALL_STATE(72)] = 1143,
  [SMALL_STATE(73)] = 1151,
  [SMALL_STATE(74)] = 1159,
  [SMALL_STATE(75)] = 1167,
  [SMALL_STATE(76)] = 1175,
  [SMALL_STATE(77)] = 1183,
  [SMALL_STATE(78)] = 1193,
  [SMALL_STATE(79)] = 1203,
  [SMALL_STATE(80)] = 1211,
  [SMALL_STATE(81)] = 1221,
  [SMALL_STATE(82)] = 1231,
  [SMALL_STATE(83)] = 1241,
  [SMALL_STATE(84)] = 1251,
  [SMALL_STATE(85)] = 1258,
  [SMALL_STATE(86)] = 1265,
  [SMALL_STATE(87)] = 1272,
  [SMALL_STATE(88)] = 1279,
  [SMALL_STATE(89)] = 1286,
  [SMALL_STATE(90)] = 1293,
  [SMALL_STATE(91)] = 1300,
  [SMALL_STATE(92)] = 1307,
  [SMALL_STATE(93)] = 1314,
  [SMALL_STATE(94)] = 1321,
  [SMALL_STATE(95)] = 1328,
  [SMALL_STATE(96)] = 1335,
  [SMALL_STATE(97)] = 1342,
  [SMALL_STATE(98)] = 1349,
  [SMALL_STATE(99)] = 1356,
  [SMALL_STATE(100)] = 1363,
  [SMALL_STATE(101)] = 1370,
  [SMALL_STATE(102)] = 1377,
  [SMALL_STATE(103)] = 1384,
  [SMALL_STATE(104)] = 1391,
  [SMALL_STATE(105)] = 1398,
  [SMALL_STATE(106)] = 1405,
  [SMALL_STATE(107)] = 1412,
  [SMALL_STATE(108)] = 1419,
  [SMALL_STATE(109)] = 1426,
  [SMALL_STATE(110)] = 1433,
  [SMALL_STATE(111)] = 1440,
  [SMALL_STATE(112)] = 1447,
  [SMALL_STATE(113)] = 1454,
  [SMALL_STATE(114)] = 1461,
  [SMALL_STATE(115)] = 1468,
  [SMALL_STATE(116)] = 1475,
  [SMALL_STATE(117)] = 1482,
  [SMALL_STATE(118)] = 1489,
  [SMALL_STATE(119)] = 1496,
  [SMALL_STATE(120)] = 1503,
  [SMALL_STATE(121)] = 1510,
  [SMALL_STATE(122)] = 1517,
  [SMALL_STATE(123)] = 1524,
  [SMALL_STATE(124)] = 1531,
  [SMALL_STATE(125)] = 1538,
  [SMALL_STATE(126)] = 1545,
  [SMALL_STATE(127)] = 1552,
  [SMALL_STATE(128)] = 1559,
  [SMALL_STATE(129)] = 1566,
  [SMALL_STATE(130)] = 1573,
  [SMALL_STATE(131)] = 1580,
  [SMALL_STATE(132)] = 1587,
  [SMALL_STATE(133)] = 1594,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(132),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 12, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_statement, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 11, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [248] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_newline] = sym_newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
  },
  [2] = {
    [ts_external_token_dedent] = true,
  },
  [3] = {
    [ts_external_token_newline] = true,
  },
  [4] = {
    [ts_external_token_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_nyx_external_scanner_create(void);
void tree_sitter_nyx_external_scanner_destroy(void *);
bool tree_sitter_nyx_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_nyx_external_scanner_serialize(void *, char *);
void tree_sitter_nyx_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nyx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_nyx_external_scanner_create,
      tree_sitter_nyx_external_scanner_destroy,
      tree_sitter_nyx_external_scanner_scan,
      tree_sitter_nyx_external_scanner_serialize,
      tree_sitter_nyx_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "nyx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
